config/routes.rb
Rails.application.routes.draw do
  root 'pages#welcome'

  get 'pages/analytics' => 'pages#analytics'
  get 'pages/cal_data' => 'pages#cal_data'

  resources :charges



  get 'search/listings' => 'searches#listings'
  post 'listings/:listing_id/charge' => 'reservations#charge', as: 'reservation_charge'

  get 'reservations/show_upcoming' => 'reservations#show_upcoming'
  get 'reservations/show_past' => 'reservations#show_past'
  get 'listings/show_clubs' => 'listings#show_clubs'
  get 'listings/show_club_sets' => 'listings#show_club_sets'
  get 'listings/:id/details' => 'listings#details'
  delete 'listings/:id/details' => 'listings#destroy'
  resources :clubs, only: [:index]
  resources :club_sets, only: [:index]

  resources :users do
    # get 'users/:user_id/clubs/new' => 'users#clubs', as: 'clubs'
    # resources :listings, except: [:index]
    # resources :reservations
    resources :reviews
  end

  resources :renters do
    resources :reservations
  end

  resources :suppliers do
    get 'listings' => 'listings#supplier_listings'
    resources :clubs do
      resources :listings, except: [:index]
    end
    resources :club_sets do
      resources :listings, except: [:index]
    end
  end

  get 'listings/four_listings/:start_row' => 'listings#four_listings', as: 'four_listings'

  resources :listings do
    resources :reservations
    resources :reviews
  end



  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

###### API V1 ################

  namespace :api do
   namespace :v1 do

     resources :listings
     resources :users
     resources :suppliers
     resources :clubs

   end
 end

end

app/models/club.rb
# == Schema Information
#
# Table name: clubs
#
#  id              :integer          not null, primary key
#  supplier_id     :integer
#  generic_club_id :integer
#  condition       :string
#  picture         :string
#  active          :boolean          default(TRUE)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Club < ActiveRecord::Base
  has_many :club_set_clubs
  has_many :club_sets, through: :club_set_clubs
  belongs_to :generic_club
  belongs_to :supplier
  has_many :listings, as: :listable

  after_save :club_set_member

  # These conditions were taken from Kelley Blue Book
  Conditions = ['excellent','very_good','good','fair']

  def self.find_by_generic_clubs(generic_club_array)
    where(generic_club:generic_club_array).where(active:true)
  end

  def self.active_clubs
    Club.where(active:true)
  end

  def generic_club_attributes=(generic_club_attributes_hash)
    generic_club = GenericClub.find_or_create_by(generic_club_attributes_hash)
    self.generic_club_id = generic_club.id
  end

  def club_attributes
    "#{self.generic_club.brand} - #{self.generic_club.club_type}"
  end

  def gender_handed
    handed = generic_club.righty ? "R" : "L"
    gender = generic_club.male ? "M" : "W"
    "(#{gender}:#{handed})"
  end

  def description
    "#{generic_club.brand} #{generic_club.club_type.capitalize} #{gender_handed}"
  end

  def complete_description
    "#{description}\nHead Feature: #{generic_club.head_feature}\nShaft Stiffness: #{generic_club.shaft_stiffness}\nCondition: #{condition}"
  end

  def club_set_member
   if !self.active
      self.club_sets.each do |club_set|
        club_set.active = false
        club_set.save
      end
    end
  end
end

app/controllers/api/v1/clubs_controller.rb
class Api::V1::ClubsController < ApplicationController

  def index
    @clubs = Club.all
    render json: @clubs
  end

end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :find_supplier, except: [:index]
  before_action :find_club, only:[:destroy]

  def new
    @club = Club.new
  end

  def create
    @club = @supplier.clubs.build(club_params)
    @club.save
    index
    # if @club.save
    #   render json: {success: "Club sucessfully created!"}
    # else
    #   render json: {errors: "Error, club could not be created."}
    # end
  end

  def destroy
    @club.active = false
    @club.save
    # REPLACE WITH .club_attributes METHOD
    flash.now[:notice] = "Your club has been removed."
    # redirect_to @supplier
    render json: {errors: @club.errors.messages[:status]}
  end

  def index
    @club = Club.new
    @supplier = current_user.supplier
    new_club_form = render_to_string template: 'clubs/_new_form', locals: {club: @club, supplier: @supplier}, layout: false
    # new_club_form = render_to_string template: 'clubs/_new_table_form', locals: {club: @club, supplier: @supplier}, layout: false
    @clubs = current_user.supplier.clubs.where(active: true)
    render json: {table: ClubsJsonViewObject.new(@clubs).get_json, form: new_club_form}
  end

private

  def club_params
    params.require(:club).permit(:condition, :generic_club_attributes => [:club_type, :brand, :male, :righty, :head_feature, :shaft_stiffness])
    # department_params.permitted? => true
  end

  def find_club
    @club=Club.find(params[:id])
  end

  def find_supplier
    @supplier = Supplier.find(params[:supplier_id])
  end

end

app/helpers/club_helper.rb
module ClubHelper
end

app/views/clubs/_club.html.erb
<div class="col-md-3 car btn btn-default listing-button">
  <h5><%= "#{generic_club.brand} : #{generic_club.club_type}" %></h5>
  <h6><%= GenericClubViewObject.new(generic_club).gender_handed %></h6>
  Head Feature: <%= generic_club.head_feature %><br>
  Shaft Stiffness: <%= generic_club.shaft_stiffness %><br>
  Condition: <%= club.condition %><br>
  <%= button_to 'Delete', supplier_club_path(supplier, club), method: :delete %>
  <%= render partial: 'listings/new_form', locals: {obj: club} %>
</div>

app/views/clubs/_club_handlebars.html.erb
<script id="entry-template" type="text/x-handlebars-template">
  <li>
    <p>
      <h5>{{listable.generic_club.brand}} : {{listable.generic_club.club_type}}</h5>
      <h6>{{listable.id}}</h6>
      Head Feature {{listable.generic_club.head_feature}} <br>
      Shaft Stiffness {{listable.generic_club.shaft_stiffness}} <br>
      Condition {{listable.condition}} <br>
    </p>
  </li>
</script>

app/views/clubs/_new_form.html.erb
<div id='new_club_container'>
  <hr>
  <div id='club-form-notice'><%= flash[:notice] %></div>
  <h5><strong><u>Add Club</u></strong></h5>
  <%= form_for(club, url: supplier_clubs_path(supplier), remote: true) do |f| %>
    <%= f.fields_for :generic_club, GenericClub.new do |field|%>
      <p>
        <%= f.label :generic_club_type %>
        <%= field.select :club_type, GenericClub::ClubTypes %>
      </p>
      <p>
        <%= f.label :generic_club_brand %>
        <%= field.text_field :brand%>
      </p>
      <p>
        <%= f.label :gender %>:
        <%= field.radio_button :male, true, checked: true%>Male
        <%= field.radio_button :male, false%>Female
      </p>
      <p>
        <%= f.label :righty %>:
        <%= field.radio_button :righty, true, checked: true%>Righty
        <%= field.radio_button :righty, false%>Lefty
      </p>
      <p>
        <%= f.label :generic_club_head_feature %>
        <%= field.select :head_feature, GenericClub::HeadFeatures %>
      </p>
      <p>
        <%= f.label :generic_club_shaft_stiffness %>
        <%= field.select :shaft_stiffness, GenericClub::ShaftStiffnesses %>
      </p>
    <% end %>
    <p>
      <%= f.label :club_condition %>
      <%= f.select :condition, Club::Conditions %>
    </p>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>
</div>

app/views/clubs/new.html.erb
<h1>New Club</h1>

<% if @club.errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(@club.errors.count, "error") %> prohibited this club from being saved:</h2>
     <ul>
     <% @club.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
     </ul>
   </div>
 <% end %>

<%= form_for(@club, url: supplier_clubs_path(@supplier)) do |f| %>

  <%= f.fields_for :generic_club, GenericClub.new do |field|%>
    <p>
      <%= f.label :generic_club_type %>
      <%= field.select :club_type, GenericClub::ClubTypes %>
    </p>
    <p>
      <%= f.label :generic_club_brand %>
      <%= field.text_field :brand%>
    </p>
    <p>
      <%= f.label :gender %>:
      <%= field.radio_button :male, true, checked: true%>Male
      <%= field.radio_button :male, false%>Female
    </p>
    <p>
      <%= f.label :righty %>:
      <%= field.radio_button :righty, true, checked: true%>Righty
      <%= field.radio_button :righty, false%>Lefty
    </p>
    <p>
      <%= f.label :generic_club_head_feature %>
      <%= field.select :head_feature, GenericClub::HeadFeatures %>
    </p>
    <p>
      <%= f.label :generic_club_shaft_stiffness %>
      <%= field.select :shaft_stiffness, GenericClub::ShaftStiffnesses %>
    </p>
  <% end %>

  <p>
  <%= f.label :club_condition %>
  <%= f.select :condition, Club::Conditions %>
  </p>

  <%= f.submit %>
<% end %>

app/views/clubs/show.html.erb
<%= render partial: 'club', locals:{club: @club} %>