config/routes.rb
Rails.application.routes.draw do
  root 'pages#welcome'

  get 'pages/analytics' => 'pages#analytics'
  get 'pages/cal_data' => 'pages#cal_data'

  resources :charges



  get 'search/listings' => 'searches#listings'
  post 'listings/:listing_id/charge' => 'reservations#charge', as: 'reservation_charge'

  get 'reservations/show_upcoming' => 'reservations#show_upcoming'
  get 'reservations/show_past' => 'reservations#show_past'
  get 'listings/show_clubs' => 'listings#show_clubs'
  get 'listings/show_club_sets' => 'listings#show_club_sets'
  get 'listings/:id/details' => 'listings#details'
  delete 'listings/:id/details' => 'listings#destroy'
  resources :clubs, only: [:index]
  resources :club_sets, only: [:index]

  resources :users do
    # get 'users/:user_id/clubs/new' => 'users#clubs', as: 'clubs'
    # resources :listings, except: [:index]
    # resources :reservations
    resources :reviews
  end

  resources :renters do
    resources :reservations
  end

  resources :suppliers do
    get 'listings' => 'listings#supplier_listings'
    resources :clubs do
      resources :listings, except: [:index]
    end
    resources :club_sets do
      resources :listings, except: [:index]
    end
  end

  get 'listings/four_listings/:start_row' => 'listings#four_listings', as: 'four_listings'

  resources :listings do
    resources :reservations
    resources :reviews
  end



  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

###### API V1 ################

  namespace :api do
   namespace :v1 do

     resources :listings
     resources :users
     resources :suppliers
     resources :clubs

   end
 end

end

app/models/listing.rb
# == Schema Information
#
# Table name: listings
#
#  id            :integer          not null, primary key
#  listable_type :string
#  listable_id   :integer
#  start_date    :date
#  finish_date   :date
#  price         :integer
#  active        :boolean          default(TRUE)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Listing < ActiveRecord::Base
  belongs_to :listable, polymorphic: true
  delegate :user, to: :listable
  has_many :reservations
  has_many :reviews, as: :reviewable
  validates :start_date, :finish_date, :price, presence: true
  validate :valid_start_date

  ### Advanced Active Record SQL
  def self.convert_to_dollars(cents)
    (cents.to_f/100.0).round(2)
  end

  def self.find_club_listings_by_user(user)
    joins("INNER JOIN clubs ON listings.listable_id = clubs.id").
    joins("INNER JOIN suppliers ON supplier_id = suppliers.id").
    joins("INNER JOIN users ON user_id = users.id").
    where("users.id = ?", user.id).where("listable_type='Club'").where(active: true)
  end

  def self.find_club_set_listings_by_user(user)
    where(listable_type: 'ClubSet').
    select{|listing| listing.listable.clubs.first.supplier.user.id == user.id && listing.listable.active}
  end

  def self.average_price_active_club
    average_club_price = joins("INNER JOIN clubs ON listings.listable_id = clubs.id").
      where("clubs.active=true").where("listable_type='Club'").
      average("listings.price")
    convert_to_dollars(average_club_price)
  end

  def self.average_price_active_club_type
    average_price_club_type_hash = joins("INNER JOIN clubs ON listings.listable_id = clubs.id").
      joins("INNER JOIN generic_clubs ON generic_club_id = generic_clubs.id").
      where("clubs.active=true").where("listable_type='Club'").
      group("generic_clubs.club_type").
      average("listings.price")
    average_price_club_type_hash.each_with_object({}){|(k,v), hash| hash[k] = convert_to_dollars(v)}
  end

  def self.average_price_active_club_set
    average_club_set_price = joins("INNER JOIN club_sets ON listings.listable_id = club_sets.id").
      where("club_sets.active=true").where("listable_type='ClubSet'").
      average("listings.price")
    convert_to_dollars(average_club_set_price)
  end

  def self.percent_under_five
    listings_under_5 = where("price <= 500").count
    total_num_of_listings = all.count
    (listings_under_5/total_num_of_listings.to_f * 100).round(2)
  end

  def self.active_and_current
    where(active:true).where("finish_date >= ?", Date.current)
  end

  def self.number_of_uniq_club
    active_and_current.where(listable_type:'Club').pluck(:listable_id).uniq.count.to_f
  end

  def self.number_of_uniq_club_set
    active_and_current.where(listable_type:'ClubSet').pluck(:listable_id).uniq.count.to_f
  end

  def self.uniq_club_ratio
    (number_of_uniq_club/active_and_current.count * 100).round(2)
  end

  def self.uniq_club_set_ratio
    (number_of_uniq_club_set/active_and_current.count * 100).round(2)
  end

  def self.get_by_listable(listable)
    where(listable:listable).where(active:true).where("finish_date >= ?", Date.current)
  end

  def listing_range
    (start_date..finish_date).to_a
  end

  def availability
    availability_range = (self.start_date..self.finish_date).to_a
    reservations = self.reservations.select(&:persisted?)
    reservations.each do |reservation|
      availability_range -= (reservation.start_date..reservation.finish_date).to_a
    end
    remove_past_dates(availability_range)
  end

  def reservation_available?(start_date, finish_date)
    reservation_dates = (start_date..finish_date).to_a
    availability&reservation_dates == reservation_dates
  end

  def remove_past_dates(date_range)
    date_range.select{|date| date >= Date.current}
  end

  def format_date(date)
    "#{date.month}-#{date.day}-#{date.year}"
  end

  def display_price
    "%.2f" % (self.price/100.0)
  end

  private

  include Validable::StartDate

end

app/controllers/api/v1/listings_controller.rb
class Api::V1::ListingsController < ApplicationController
  def index
    @listings = Listing.all
    render json: @listings
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  # before_action :find_user, only: [:supplier_listings]
  # before_action :find_supplier, only: [:new, :create, :supplier_listings]
  # before_action :find_club, only: [:new, :create]
  # before_action :find_club_set, only: [:new, :create]
  before_action :find_supplier, only: [:supplier_listings]
  before_action :require_user, only: [:create, :show, :new, :destroy]

  def new
    @obj = Club.find_by(id: params[:club_id]) || ClubSet.find_by(id: params[:club_set_id])
    @supplier = Supplier.find_by(id: params[:supplier_id])
    # obj_json =  @obj.class == 'Club' ? ClubsJsonViewObject.new([@obj]).get_json.first : 1 # change to club set once implemented
    if @obj.class.to_s == 'Club'
      obj_json = ClubsJsonViewObject.new([@obj]).get_json
    else
      obj_json = ClubSetJsonViewObject.new(@obj).get_json
    end
    new_listing_form = render_to_string template: 'listings/_new_form', locals: {obj: @obj, supplier: @supplier}, layout: false  
    render json: {form: new_listing_form, obj: obj_json}
  end

  def index
    @listings = Listing.all
    @brands = GenericClub.brand_names
    @generic_clubs = GenericClub.all
  end

  def supplier_listings
    @club_listings = @supplier.listable_listings('clubs')
    @club_set_listings = @supplier.listable_listings('club_sets').uniq
    render 'listings/supplier_index.html.erb'
  end

  # def four_listings
  #   start_load = (params[:start_row]).to_i
  #   listings = Listing.all
  #   html_string = render_to_string 'listings/_listing_row', locals: {listings: listings, start_load:start_load}, layout: false
  #   render json: {new_row: html_string}
  # end

  def show
    @listing = Listing.find(params[:id])
    respond_to do |format|
      format.html {render :show}
      format.json {render json: ListingsJsonViewObject.new([@listing]).collect_listings_json}
    end
  end

  def details
    @listing = Listing.find(params[:id])
    render json: ListingJsonViewObject.new(@listing).get_json
  end

  def show_clubs
    @listings = Listing.find_club_listings_by_user(current_user)
    render json: ListingsTypesJsonViewObject.new(@listings).get_json
  end

  def show_club_sets
    @listings = Listing.find_club_set_listings_by_user(current_user)
    render json: ListingsTypesJsonViewObject.new(@listings).get_json
  end

  def create
    priced_params = listing_params
    priced_params[:price] = listing_params[:price].to_f * 100
    @listing = Listing.new(priced_params)

    if @listing.save
      render json: {success: 'Listing created!'}
    else
      render json: {errors: 'Dates selected are not valid.'}
    end
  end

  def destroy
    @listing = Listing.find(params[:id])
    @listing.active = false
    @listing.save
    render json: {errors: @listing}
  end

  private

  def listing_params
    params.require(:listing).permit(:start_date, :finish_date, :price, :listable_type, :listable_id)
  end

  def find_user
    @user = User.find(params[:user_id])
  end

  def find_supplier
    @supplier = Supplier.find(params[:supplier_id])
  end

  def find_club
    @club = Club.find_by(id: params[:club_id])
  end

  def find_club_set
    @club_set = ClubSet.find_by(id: params[:club_set_id])
  end
end

app/helpers/listing_helper.rb
module ListingHelper
end

app/views/listings/_charge_form_handlebars.html.erb
<script id="charges_path-template" type="text/x-handlebars-template">
  <%= form_tag reservation_charge_path(listing) do %>
    <input type='hidden' name='reservation[start_date]' value={{reservation_data.start_date}}>
    <input type='hidden' name='reservation[finish_date]' value={{reservation_data.finish_date}}>
    <input type='hidden' name='reservation[listing_id]' value={{reservation_data.listing_id}}>
    <article class='listing-show-description'>
      <strong>Start: </strong>{{start}}<br>
      <strong>End: </strong>{{end}}<br>
      <strong>Total: </strong>${{cost}}<br>
      </label>
    </article>
    <input type='button' class='btn btn-danger cancel-stripe' value='Cancel'><br><br>
    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="A month's subscription"
            data-locale="auto"></script>
  <% end %>
</script>

app/views/listings/_listing.html.erb
<div class="col-md-3 car btn btn-default listing-button">
  <h5><%= listing.listable.description%></h5>
  <p><strong>Type:</strong> <%= listing.listable_type %></p>
  <p><strong>From:</strong> <%= listing.start_date %></p>
  <input class='listing-availability' type=hidden name='listing-availability' value='<%=listing.availability%>'>
  <p><strong>To:</strong> <%= listing.finish_date %></p>
  <div class='calendar'></div>
  <p><strong>Price:</strong> <%= listing.price %></p>
  <%=link_to listing.id, listing %>
</div>

app/views/listings/_listing_handlebars.html.erb
<script id="entry-template" type="text/x-handlebars-template">
  <div class="col-md-3 car btn btn-default listing-button">
    <p><strong>{{listable.description}}</strong></p>
    <strong>Type:</strong> {{listable_type}} <br>
    <strong>Price:</strong> ${{price}} <br>
    <strong>From:</strong> {{start_date}} <br>
    <strong>To:</strong> {{finish_date}} <br>
    <input class='listing-availability' type=hidden name='listing-availability' value= {{availability}}> <br>
    <strong>Available Dates:</strong>
    <div class='calendar-container'>
        <div class='calendar'></div>
    </div>
    <a href= {{url}}>View Listing</a><br>
  </div>
</script>

app/views/listings/_listing_row.html.erb
<!-- <div class="row">
  <% listings[start_load,4].each do |listing| %>
    <%= render partial: 'listing', locals:{listing:listing}%>
  <% end %>
</div> -->

app/views/listings/_listing_show_handlebars.html.erb
<script id="entry-template" type="text/x-handlebars-template">
  <div class='container'>
  <div class='row text-center uppercase-text'>
    <h3><strong>{{listable.description}}</strong></h3>
  </div>
    <div class="col-md-4"></div>
    <div class="col-md-4 car btn btn-default listing-button">
      <div class='listing-show-description'>
        <strong>Type:</strong> {{listable_type}}<br>
        <strong>Available Dates:</strong>
        <input class='listing-availability' type=hidden name='listing-availability' value= {{availability}}> <br>
        <div class='calendar-container'>
          <div class='calendar'></div>
        </div>
        <strong>Price per day:</strong> ${{price}} <br>
        <%= form_for listing.reservations.build, url: renter_reservations_path(current_user.renter), remote: true do |f| %>
          <%= f.hidden_field :listing_id, value: listing.id %>
          <%= f.label :start_date %>
          <%= f.date_field :start_date, value: listing.start_date %><br>
          <%= f.label :finish_date %>
          <%= f.date_field :finish_date, value: listing.finish_date %><br>
          <%= f.submit %> 
        <% end %>
      </div>
    </div>
    <div class="col-md-4"></div>
  </div>
</script>

app/views/listings/_new_form.html.erb
<div id='listing-form-notice'><%= flash[:notice] %></div>
<%= form_for obj.listings.build, remote: true, class: 'form-horizontal' do |f| %>
  <fieldset>
    <h5><strong><u>Create Listing</u></strong></h5>
    <%= f.hidden_field :user_id, value: supplier.user.id %>
    <%= f.hidden_field :listable_id, value: obj.id %>
    <%= f.hidden_field :listable_type, value: obj.class.to_s %>
    <%= f.label :start_date, class: "control-label" %>
    <%= f.date_field :start_date, value: Date.current, class: "form-control" %><br>
    <%= f.label :finish_date, class: "control-label" %>
    <%= f.date_field :finish_date, class: "form-control" %><br>
    <%= f.label :price, class: "control-label" %>
    <%= f.text_field :price, class: "form-control" %><br>
    <%= f.submit class: "btn btn-primary" %> 
  </fieldset>
<% end %>

app/views/listings/_old_listing.html.erb
<tr>
  <th><%=link_to listing.id, listing %></th>
  <th><%= listing.listable_type %></th>
  <th><%= listing.listable.description%></th>
  <th><%= listing.start_date %></th>
  <th><%= listing.finish_date %></th>
  <th><%= listing.price %></th>
</tr>

app/views/listings/_supplier_index_row.html.erb
<tr>
  <td width='50%'><%= listing.listable.class %>: <%= listing.listable.description %></td>
  <td width='15%'><%= listing.format_date(listing.start_date) %></td>
  <td width='15%'><%= listing.format_date(listing.finish_date) %></td>
  <td width='10%'>$<%= listing.display_price %></td>
  <td width='10%'><%= button_to 'Remove', {:controller => :listings, :action => 'destroy', id: listing.id }, :method => :delete, class: 'cancel-listing', remote: true, data: {confirm: "Are you sure?"} %></td>
</tr>

app/views/listings/_supplier_index_table.html.erb
<div class=<%= div_class %>>
  <div class='col-md-1'></div>
  <div class='col-md-10'>
    <table class="table table-striped table-hover ">
      <h2 class='reservations-header'><%= header %></h2>
      <thead>
        <tr>
          <th width='50%'>Type</th>
          <th width='15%'>Start</th>
          <th width='15%'>End</th>
          <th width='10%'>Price</th>
          <th width='10%'>Options</th>
        </tr>
      </thead>
      <tbody>
        <% listings.each do |listing| %>
          <%= render partial: 'supplier_index_row', locals: {listing: listing} %>
        <% end %>
      </tbody>
    </table> 
  </div>
  <div class='col-md-1'></div>
</div>

app/views/listings/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <br>
      <%= form_for GenericClub.new, url:'/search/listings', method:'get', html:{id:'listings-search'}, remote:true do |f| %>
      <%= f.submit "Search Clubs and Sets", class: 'btn btn-success'%>
      <hr>
      <p>
        Search Type: <br>
        <%= radio_button_tag 'search_type', 'club_set', true%> Club Set <br>
        <%= radio_button_tag 'search_type', 'club'%> Club
      </p>
      <hr>
        <p>
          Gender: <br>
          <%= f.radio_button :male, true, checked: true%>Male <br>
          <%= f.radio_button :male, false%>Female
        </p>
        <hr>
        <p>
          Hand: <br>
          <%= f.radio_button :righty, true, checked: true%>Right Handed <br>
          <%= f.radio_button :righty, false%>Left Handed
        </p>
        <hr>
        <p>
          Club Type: <br>
          <%= collection_check_boxes(:generic_club, :club_type, GenericClub::ClubTypes, :to_s, :to_s) do |b| %>
            <% b.label(class: 'collection-check-box') { b.check_box + b.text } %>
          <% end %>
        </p>
        <hr>
        <p>
          Head Feature: <br>
          <%= collection_check_boxes(:generic_club, :head_feature, GenericClub::HeadFeatures, :to_s, :to_s) do |b| %>
            <% b.label(class: 'collection-check-box') { b.check_box + b.text } %>
          <% end %>
        </p>
        <hr>
        <p>
          Head Feature: <br>
          <%= collection_check_boxes(:generic_club, :shaft_stiffness, GenericClub::ShaftStiffnesses, :to_s, :to_s) do |b|%>
            <% b.label(class: 'collection-check-box') { b.check_box + b.text } %>
          <% end %>
        </p>
        <hr>

      <% end %>
    </div>


    <!-- Search results go in here -->
    <div class="col-md-9 search-results">
      <h2>&#8606 Search For Some Clubs</h2>
    </div>
    <!-- end search results -->


  </div>

</div>

<%= render partial: 'listings/listing_handlebars' %>

app/views/listings/new.html.erb
<% if @club %>
  <%= render :partial => 'new_form', locals: {listing: @listing, url: supplier_club_listings_path(@supplier, @club)} %>
<% else %>
  <%= render :partial => 'new_form', locals: {listing: @listing, url: supplier_club_set_listings_path(@supplier, @club_set)} %>
<% end %>

app/views/listings/old_index.html.erb
<table>
  <thead>
    <tr>
      <th>Listing ID</th>
      <th>Type</th>
      <th>Description</th>
      <th>Start</th>
      <th>End</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
    <% @listings.each do |listing| %>
      <%= render partial: 'listing', locals:{listing:listing}%>
    <% end %>
  </tbody>
</table>

app/views/listings/show.html.erb
<%= render partial: 'listings/listing_show_handlebars', locals:{listing: @listing} %>

<%= render partial: 'listings/charge_form_handlebars', locals:{listing: @listing} %>

<script type="text/javascript">
  $(function(){
    var url_array = this.URL.split('/');
    var listing_id = url_array[url_array.length-1];
    $.getJSON(listing_id, function(data){
      var source = $('#entry-template').html();
      var template = Handlebars.compile(source);
      var listings = data.listings;
      $('.search-results').html('')
      var listing_results = ""
      listings.forEach(function(listing){
        var listing_html = template(listing);
        listing_results = listing_results + listing_html
      })
      $(listing_results).appendTo('body')
      attachCalendar();

      $('form.new_reservation').on('ajax:complete', function(event, data, status, xhr){
        $('#flash-notice').empty()
        var jsonData = data.responseJSON
        if(jsonData.notice.length == 0) {
          var source = $('#charges_path-template').html();
          var template = Handlebars.compile(source);
          $(template(jsonData.form_data)).appendTo('div.listing-button');
          $(this).toggleClass('hide-form');

          $('.cancel-stripe').on('click', function(){
            $('#new_reservation').toggleClass('hide-form');
            $(this).parent().remove()
          });

        } else {
          $('#flash-notice').text('Invalid reservation dates');
        }
      });
    });
  })
</script>

app/views/listings/supplier_index.html.erb
<%= render partial: 'supplier_index_table', locals: {listings: @club_listings, div_class: 'row supplier-club-listings', header: 'My Club Listings'} %>

<%= render partial: 'supplier_index_table', locals: {listings: @club_set_listings, div_class: 'row supplier-club-listings', header: 'My Set Listings'} %>