config/routes.rb
Rails.application.routes.draw do
  root 'pages#welcome'

  get 'pages/analytics' => 'pages#analytics'
  get 'pages/cal_data' => 'pages#cal_data'

  resources :charges



  get 'search/listings' => 'searches#listings'
  post 'listings/:listing_id/charge' => 'reservations#charge', as: 'reservation_charge'

  get 'reservations/show_upcoming' => 'reservations#show_upcoming'
  get 'reservations/show_past' => 'reservations#show_past'
  get 'listings/show_clubs' => 'listings#show_clubs'
  get 'listings/show_club_sets' => 'listings#show_club_sets'
  get 'listings/:id/details' => 'listings#details'
  delete 'listings/:id/details' => 'listings#destroy'
  resources :clubs, only: [:index]
  resources :club_sets, only: [:index]

  resources :users do
    # get 'users/:user_id/clubs/new' => 'users#clubs', as: 'clubs'
    # resources :listings, except: [:index]
    # resources :reservations
    resources :reviews
  end

  resources :renters do
    resources :reservations
  end

  resources :suppliers do
    get 'listings' => 'listings#supplier_listings'
    resources :clubs do
      resources :listings, except: [:index]
    end
    resources :club_sets do
      resources :listings, except: [:index]
    end
  end

  get 'listings/four_listings/:start_row' => 'listings#four_listings', as: 'four_listings'

  resources :listings do
    resources :reservations
    resources :reviews
  end



  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

###### API V1 ################

  namespace :api do
   namespace :v1 do

     resources :listings
     resources :users
     resources :suppliers
     resources :clubs

   end
 end

end

app/models/reservation.rb
# == Schema Information
#
# Table name: reservations
#
#  id          :integer          not null, primary key
#  renter_id   :integer
#  start_date  :date
#  finish_date :date
#  listing_id  :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Reservation < ActiveRecord::Base
  has_many :reviews, as: :reviewable
  belongs_to :renter
  belongs_to :listing
  delegate :supplier, to: :listing
  validates :start_date, :finish_date, presence: true
  validate :reservation_available_validation, :valid_start_date

  before_destroy :valid_deletion
  # after_create :verify_listing

  ### Advanced Active Record SQL
  def self.club_reservations

  end

  def self.upcoming_reservations_by(obj)
    self.where(obj.class.to_s.downcase.to_sym => obj).where("finish_date >= ?", Date.current)
  end

  def self.past_reservations_by(obj)
    self.where(obj.class.to_s.downcase.to_sym => obj).where("finish_date < ?", Date.current)
  end

  def format_date(date)
    "#{date.month}-#{date.day}-#{date.year}"
  end

  def total_cost
    number_of_days = (self.start_date..self.finish_date).to_a.count
    number_of_days * self.listing.price
  end

  def display_total_cost
    "%.2f" % (self.total_cost/100.0)
  end

  private

  include Validable::StartDate

  # def verify_listing
  #   binding.pry
  #   if self.listing.listable_type == "Club"
  #     reservation_start_date = self.start_date
  #     reservation_finish_date = self.finish_date
  #     reservation_dates = (self.start_date..self.finish_date).to_a

  #     listing_start_date = self.listing.start_date
  #     listing_finish_date = self.listing.finish_date
  #     listing_dates = (self.listing.start_date..self.listing.finish_date).to_a

  #   end

  # end

  def valid_deletion
    if Date.current + 7 >= self.start_date
      errors.add(:status, "cannot cancel a reservation 7 days prior to start date")
      return false
    end
  end

  def reservation_available_validation
    if (self.start_date && self.finish_date)
      if !self.listing.reservation_available?(self.start_date, self.finish_date)
        errors.add(:status, "invalid reservation")
      end
    end
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :find_renter, only: [:index, :create, :show, :destroy]
  before_action :find_reservation, only: [:destroy, :show]
  before_action :find_supplier, only: [:show, :create, :new, :charge, :show,]

  def new
    @listing = Listing.find(params[:listing_id])
    @reservation = Reservation.new
  end

  def create
    @reservation = @renter.reservations.build(reservation_params)
    @listing = Listing.find(@reservation.listing_id)
    @reservation.valid?
    render json: ReservationJsonViewObject.new(@reservation).get_json_for_reservation
  end

  def charge
    @renter = Renter.find(current_user.renter.id)
    @reservation = @renter.reservations.build(reservation_params)
    @reservation.save
    flash[:notice] = 'Reservation Confirmed!'
    redirect_to current_user
  end

  def index
    @upcoming_reservations = Reservation.upcoming_reservations_by(@renter)
    @past_reservations = Reservation.past_reservations_by(@renter)
  end

  def show
    # @supplier = @reservation.listing.listable.supplier.user
    render json: ReservationDetailsViewObject.new(@reservation).get_json
  end

  def show_upcoming
    @upcoming_reservations = Reservation.upcoming_reservations_by(current_user.renter)
    render json: {reservations: ReservationsJsonViewObject.new(@upcoming_reservations).get_json }
  end

  def show_past
    @past_reservations = Reservation.past_reservations_by(current_user.renter)
    render json: {reservations: ReservationsJsonViewObject.new(@past_reservations).get_json }
  end

  def destroy
    @reservation.destroy
    render json: {errors: @reservation.errors.messages[:status]}
  end

  private

  def reservation_params
    params.require(:reservation).permit(:start_date, :finish_date, :listing_id)
  end

  def find_renter
    @renter = current_user.renter
  end

  def find_reservation
    @reservation = Reservation.find(params[:id])
  end

  def find_supplier
    @supplier = current_user.supplier
  end
end

app/helpers/reservation_helper.rb
module ReservationHelper
end

app/views/reservations/_index_table.html.erb
<div class=<%= div_class %>>
  <div class='col-md-1'></div>
  <div class='col-md-10'>
    <table class="table table-striped table-hover ">
      <h2 class='reservations-header'><%= header %></h2>
      <thead>
        <tr>
          <th width='50%'>Type</th>
          <th width='15%'>Start</th>
          <th width='15%'>End</th>
          <th width='10%'>Total</th>
          <th width='10%'>Options</th>
        </tr>
      </thead>
      <tbody>
        <% reservations.each do |reservation| %>
          <%= render partial: 'index_table_row', locals: {renter: current_user.renter, reservation: reservation} %>
        <% end %>
      </tbody>
    </table> 
  </div>
  <div class='col-md-1'></div>
</div>

app/views/reservations/_index_table_row.html.erb
<tr>
  <td width='50%'><%= link_to "#{reservation.listing.listable.class} : #{reservation.listing.listable.description}", renter_reservation_path(renter, reservation) %></td>
  <td width='15%'><%= reservation.format_date(reservation.start_date) %></td>
  <td width='15%'><%= reservation.format_date(reservation.finish_date) %></td>
  <td width='10%'>$<%= reservation.display_total_cost %></td>
  <td width='10%'><%= button_to 'Cancel', {:controller => :reservations, :action => 'destroy', :renter_id => reservation.renter.id, id: reservation.id }, :method => :delete, class: 'cancel-reservation', remote: true, data: {confirm: "Are you sure?"} %></td>
</tr>

app/views/reservations/_new_form.html.erb
<div class="container" >
<button class="create_form_btn" >Reserve</button>

<%= form_for listing.reservations.build, url: renter_reservations_path(current_user.renter), html: {class: 'hide-form'} do |f| %>
  <%= f.hidden_field :listing_id, value: listing.id %>
  <%= f.label :start_date %>
  <%= f.date_field :start_date, value: listing.start_date %>
  <%= f.label :finish_date %>
  <%= f.date_field :finish_date, value: listing.finish_date %>
  <%= f.submit %> 
  <%= f.submit "Cancel", type: "button", class: "btn-cancel" %>
<% end %>
</div>

app/views/reservations/index.html.erb
<%= render partial: 'index_table', locals: {reservations: @upcoming_reservations, div_class: 'row upcoming-reservations', header: 'Upcoming Reservations'} %>

<%= render partial: 'index_table', locals: {reservations: @past_reservations, div_class: 'row past-reservations', header: 'Past Reservations'} %>

app/views/reservations/new.html.erb
<%= form_for @reservation, url: listing_reservations_path(id: @listing.id) do |f| %>
  <%= f.label :start_date %>
  <%= f.date_field :start_date, value: @listing.start_date %>
  <%= f.label :finish_date %>
  <%= f.date_field :finish_date, value: @listing.finish_date %>
  <%= f.submit %>
<% end %>

app/views/reservations/show.html.erb
<div class="reservation-show">
  <h3>Reservation Details:</h3>
  <p><strong>Host: </strong><%= @supplier.full_name %></p>
  <p><strong>Pick-up Location: </strong><%= @supplier.address %></p>
  <br>
  <p><strong>Start Date: </strong><%= @reservation.format_date(@reservation.start_date) %></p>
  <p><strong>End Date: </strong><%= @reservation.format_date(@reservation.finish_date) %></p>
  <p><strong>Total: </strong>$<%= @reservation.display_total_cost %></p>
  <%= button_to 'Cancel', {:controller => :reservations, :action => 'destroy', :renter_id => @reservation.renter.id, id: @reservation.id }, :method => :delete, class: 'cancel-reservation', data: {confirm: "Are you sure?"} %>
</div>