config/routes.rb
Rails.application.routes.draw do
  root 'pages#welcome'

  get 'pages/analytics' => 'pages#analytics'
  get 'pages/cal_data' => 'pages#cal_data'

  resources :charges



  get 'search/listings' => 'searches#listings'
  post 'listings/:listing_id/charge' => 'reservations#charge', as: 'reservation_charge'

  get 'reservations/show_upcoming' => 'reservations#show_upcoming'
  get 'reservations/show_past' => 'reservations#show_past'
  get 'listings/show_clubs' => 'listings#show_clubs'
  get 'listings/show_club_sets' => 'listings#show_club_sets'
  get 'listings/:id/details' => 'listings#details'
  delete 'listings/:id/details' => 'listings#destroy'
  resources :clubs, only: [:index]
  resources :club_sets, only: [:index]

  resources :users do
    # get 'users/:user_id/clubs/new' => 'users#clubs', as: 'clubs'
    # resources :listings, except: [:index]
    # resources :reservations
    resources :reviews
  end

  resources :renters do
    resources :reservations
  end

  resources :suppliers do
    get 'listings' => 'listings#supplier_listings'
    resources :clubs do
      resources :listings, except: [:index]
    end
    resources :club_sets do
      resources :listings, except: [:index]
    end
  end

  get 'listings/four_listings/:start_row' => 'listings#four_listings', as: 'four_listings'

  resources :listings do
    resources :reservations
    resources :reviews
  end



  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

###### API V1 ################

  namespace :api do
   namespace :v1 do

     resources :listings
     resources :users
     resources :suppliers
     resources :clubs

   end
 end

end

app/views/layouts/_logged_in_nav.html.erb
<% if logged_in?  %>
  <li>
    <%= link_to 'Profile', user %>
  </li>
  <li>
    <%=link_to 'Logout', logout_path, method: :delete %>
  </li>
<% else %>
  <li><%=link_to 'Login', login_path %></li><li><%=link_to 'Sign up', new_user_path %></li>
<% end %>

app/views/layouts/_nav_bar_2.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Git-A-Club</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/pages/analytics">Analytics</a></li>
        <li><a href="/listings">Listings</a></li>
        <%= render partial: 'layouts/logged_in_nav', locals:{user:current_user} %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navbar.html.erb
<% if logged_in? %>
  Welcome <%=link_to current_user.first_name.capitalize, current_user %>!
  <%=link_to 'Logout', logout_path, method: :delete %>
<%else%>
  <%=link_to 'Login', login_path %>
  <%=link_to 'Sign up', new_user_path %>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GitAClub</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/nav_bar_2' %>
<h3 id='flash-notice' class="text-warning"><%= flash[:notice] %></h3>

<%= yield %>

</body>
</html>